"""バトルフェイズ (SelectionType:2) & 値無し (SelectionId:-1)"""

OPTIONS = {
    "card_id:None|command_type:CHANGE_PHASE|phase:END|is_powerful:FALSE": {
        "card_id": -1,
        "command_type": 3,
        "phase": 5,
        "is_powerful": False,
    },
    "card_id:None|command_type:CHANGE_PHASE|phase:MAIN2|is_powerful:FALSE": {
        "card_id": -1,
        "command_type": 3,
        "phase": 4,
        "is_powerful": False,
    },
    "card_id:洞窟に潜む竜|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1001,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:洞窟に潜む竜|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1001,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:サファイアドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1002,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:サファイアドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1002,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:アレキサンドライドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1003,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:アレキサンドライドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1003,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:青眼の白龍|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1004,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:アサルトワイバーン|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1005,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:アサルトワイバーン|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1005,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:仮面竜|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1017,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:仮面竜|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1017,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:ボマー・ドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1018,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:ボマー・ドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1018,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:コドモドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1019,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:コドモドラゴン|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1019,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:センジュ・ゴッド|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1020,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:センジュ・ゴッド|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1020,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:ソニックバード|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1021,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:ソニックバード|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1021,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:マンジュ・ゴッド|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1022,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:マンジュ・ゴッド|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1022,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:創世の竜騎士|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1023,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:創世の竜騎士|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1023,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:白竜の聖騎士|command_type:ATTACK|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1024,
        "command_type": 2,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:白竜の聖騎士|command_type:ATTACK|phase:NO_VALUE|is_powerful:TRUE": {
        "card_id": 1024,
        "command_type": 2,
        "phase": -1,
        "is_powerful": True,
    },
    "card_id:収縮|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1011,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:銀龍の轟咆|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1012,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:強化蘇生|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1016,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:月の書|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1028,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:禁じられた聖槍|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1029,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:戦線復帰|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1030,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
    "card_id:リビングデッドの呼び声|command_type:ACTIVATE|phase:NO_VALUE|is_powerful:FALSE": {
        "card_id": 1031,
        "command_type": 0,
        "phase": -1,
        "is_powerful": False,
    },
}
