"""チェーンに積まれる前の処理中 (SelectionType:9) & 手札を捨ててください。 (SelectionId:23)"""

OPTIONS = {
    "card_id:洞窟に潜む竜": {"card_id": 1001},
    "card_id:アレキサンドライドラゴン": {"card_id": 1003},
    "card_id:青眼の白龍": {"card_id": 1004},
    "card_id:アサルトワイバーン": {"card_id": 1005},
    "card_id:大嵐": {"card_id": 1007},
    "card_id:サイクロン": {"card_id": 1010},
    "card_id:収縮": {"card_id": 1011},
    "card_id:聖なるバリア －ミラーフォース－": {"card_id": 1013},
    "card_id:砂塵の大竜巻": {"card_id": 1014},
    "card_id:激流葬": {"card_id": 1015},
    "card_id:強化蘇生": {"card_id": 1016},
    "card_id:仮面竜": {"card_id": 1017},
    "card_id:センジュ・ゴッド": {"card_id": 1020},
    "card_id:マンジュ・ゴッド": {"card_id": 1022},
    "card_id:創世の竜騎士": {"card_id": 1023},
    "card_id:白竜の聖騎士": {"card_id": 1024},
    "card_id:死者蘇生": {"card_id": 1025},
    "card_id:白竜降臨": {"card_id": 1026},
    "card_id:高等儀式術": {"card_id": 1027},
    "card_id:月の書": {"card_id": 1028},
    "card_id:戦線復帰": {"card_id": 1030},
    "card_id:リビングデッドの呼び声": {"card_id": 1031},
}
